services:
  db:
    image: postgres:13
    container_name: ai-memory-db
    environment:
      POSTGRES_USER: ailuke
      POSTGRES_PASSWORD: mypassword123456
      POSTGRES_DB: aimemory
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
